name: release

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

jobs:
  npm-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Publish npm package
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ".npmrc"
          npm publish ./
